metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true


processors:
- add_docker_metadata: ~


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["elk:9200"]


logging.to_files: false


setup:
  kibana.host: "elk:5601"
  dashboards.enabled: true