filebeat.registry_file: /usr/share/filebeat/data/registry


filebeat.config.inputs:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false


filebeat.modules:

#Filebeat system module consumes logs from host OS through a mounted volume.
- module: system
  syslog:
    var.paths: ["/var/log/host/system.log*"]


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["elk:9200"]


logging.to_files: false


setup:
  kibana.host: "elk:5601"
  dashboards.enabled: true